http:
  routers:
    grafana:
      rule: "Host(`grafana.local`)"
      entrypoints:
        - web
      service: grafana
  services:
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"

